language: python
python:
  - "2.7"
cache: pip
before_install:
    - pip install pytest pytest-cov
install:
  - pip install -r requirements.txt
script:
  - coverage run py.test
after_success:
  - codecov
